// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE55FqsjXBGRrDxq-JPflSon1qTLOX9fc',
    appId: '1:682281095463:web:4e9533c1c30e6919e55902',
    messagingSenderId: '682281095463',
    projectId: 'fruit-hub-99ac9',
    authDomain: 'fruit-hub-99ac9.firebaseapp.com',
    storageBucket: 'fruit-hub-99ac9.firebasestorage.app',
    measurementId: 'G-QRRZWVJLB5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAleWTWqAhcoDdzO5UGsxVXLCE7iJg9JC8',
    appId: '1:682281095463:android:c6ffa32a153b3e31e55902',
    messagingSenderId: '682281095463',
    projectId: 'fruit-hub-99ac9',
    storageBucket: 'fruit-hub-99ac9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvGfyBI-hSTKmyYD9NKGS6y08xlxeHKeg',
    appId: '1:682281095463:ios:4c99e216164f2cabe55902',
    messagingSenderId: '682281095463',
    projectId: 'fruit-hub-99ac9',
    storageBucket: 'fruit-hub-99ac9.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvGfyBI-hSTKmyYD9NKGS6y08xlxeHKeg',
    appId: '1:682281095463:ios:4c99e216164f2cabe55902',
    messagingSenderId: '682281095463',
    projectId: 'fruit-hub-99ac9',
    storageBucket: 'fruit-hub-99ac9.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE55FqsjXBGRrDxq-JPflSon1qTLOX9fc',
    appId: '1:682281095463:web:54148565bb0e38d5e55902',
    messagingSenderId: '682281095463',
    projectId: 'fruit-hub-99ac9',
    authDomain: 'fruit-hub-99ac9.firebaseapp.com',
    storageBucket: 'fruit-hub-99ac9.firebasestorage.app',
    measurementId: 'G-MQC15E3LPE',
  );
}
